abi3 = [{"anonymous": False,
         "inputs": [{"indexed": True, "internalType": "address", "name": "_owner", "type": "address"},
                    {"indexed": True, "internalType": "address", "name": "_operator", "type": "address"},
                    {"indexed": False, "internalType": "bool", "name": "_approved", "type": "bool"}],
         "name": "PetOperatorApprovalForAll", "type": "event"},
        {"inputs": [{"internalType": "uint256", "name": "_tokenId", "type": "uint256"}], "name": "aavegotchiClaimTime",
         "outputs": [{"internalType": "uint256", "name": "claimTime_", "type": "uint256"}], "stateMutability": "view",
         "type": "function"},
        {"inputs": [{"internalType": "address", "name": "_owner", "type": "address"}], "name": "allAavegotchisOfOwner",
         "outputs": [{"components": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"},
                                     {"internalType": "string", "name": "name", "type": "string"},
                                     {"internalType": "address", "name": "owner", "type": "address"},
                                     {"internalType": "uint256", "name": "randomNumber", "type": "uint256"},
                                     {"internalType": "uint256", "name": "status", "type": "uint256"},
                                     {"internalType": "int16[6]", "name": "numericTraits", "type": "int16[6]"},
                                     {"internalType": "int16[6]", "name": "modifiedNumericTraits", "type": "int16[6]"},
                                     {"internalType": "uint16[16]", "name": "equippedWearables", "type": "uint16[16]"},
                                     {"internalType": "address", "name": "collateral", "type": "address"},
                                     {"internalType": "address", "name": "escrow", "type": "address"},
                                     {"internalType": "uint256", "name": "stakedAmount", "type": "uint256"},
                                     {"internalType": "uint256", "name": "minimumStake", "type": "uint256"},
                                     {"internalType": "uint256", "name": "kinship", "type": "uint256"},
                                     {"internalType": "uint256", "name": "lastInteracted", "type": "uint256"},
                                     {"internalType": "uint256", "name": "experience", "type": "uint256"},
                                     {"internalType": "uint256", "name": "toNextLevel", "type": "uint256"},
                                     {"internalType": "uint256", "name": "usedSkillPoints", "type": "uint256"},
                                     {"internalType": "uint256", "name": "level", "type": "uint256"},
                                     {"internalType": "uint256", "name": "hauntId", "type": "uint256"},
                                     {"internalType": "uint256", "name": "baseRarityScore", "type": "uint256"},
                                     {"internalType": "uint256", "name": "modifiedRarityScore", "type": "uint256"},
                                     {"internalType": "bool", "name": "locked", "type": "bool"}, {"components": [
                 {"internalType": "uint256", "name": "balance", "type": "uint256"},
                 {"internalType": "uint256", "name": "itemId", "type": "uint256"}, {
                     "components": [{"internalType": "string", "name": "name", "type": "string"},
                                    {"internalType": "string", "name": "description", "type": "string"},
                                    {"internalType": "string", "name": "author", "type": "string"},
                                    {"internalType": "int8[6]", "name": "traitModifiers", "type": "int8[6]"},
                                    {"internalType": "bool[16]", "name": "slotPositions", "type": "bool[16]"},
                                    {"internalType": "uint8[]", "name": "allowedCollaterals", "type": "uint8[]"}, {
                                        "components": [{"internalType": "uint8", "name": "x", "type": "uint8"},
                                                       {"internalType": "uint8", "name": "y", "type": "uint8"},
                                                       {"internalType": "uint8", "name": "width", "type": "uint8"},
                                                       {"internalType": "uint8", "name": "height", "type": "uint8"}],
                                        "internalType": "struct Dimensions", "name": "dimensions", "type": "tuple"},
                                    {"internalType": "uint256", "name": "ghstPrice", "type": "uint256"},
                                    {"internalType": "uint256", "name": "maxQuantity", "type": "uint256"},
                                    {"internalType": "uint256", "name": "totalQuantity", "type": "uint256"},
                                    {"internalType": "uint32", "name": "svgId", "type": "uint32"},
                                    {"internalType": "uint8", "name": "rarityScoreModifier", "type": "uint8"},
                                    {"internalType": "bool", "name": "canPurchaseWithGhst", "type": "bool"},
                                    {"internalType": "uint16", "name": "minLevel", "type": "uint16"},
                                    {"internalType": "bool", "name": "canBeTransferred", "type": "bool"},
                                    {"internalType": "uint8", "name": "category", "type": "uint8"},
                                    {"internalType": "int16", "name": "kinshipBonus", "type": "int16"},
                                    {"internalType": "uint32", "name": "experienceBonus", "type": "uint32"}],
                     "internalType": "struct ItemType", "name": "itemType", "type": "tuple"}],
                                                                                                  "internalType": "struct ItemTypeIO[]",
                                                                                                  "name": "items",
                                                                                                  "type": "tuple[]"}],
                      "internalType": "struct AavegotchiInfo[]", "name": "aavegotchiInfos_", "type": "tuple[]"}],
         "stateMutability": "view", "type": "function"}, {
            "inputs": [{"internalType": "address", "name": "_approved", "type": "address"},
                       {"internalType": "uint256", "name": "_tokenId", "type": "uint256"}], "name": "approve",
            "outputs": [], "stateMutability": "nonpayable", "type": "function"},
        {"inputs": [{"internalType": "address", "name": "_owner", "type": "address"}], "name": "balanceOf",
         "outputs": [{"internalType": "uint256", "name": "balance_", "type": "uint256"}], "stateMutability": "view",
         "type": "function"},
        {"inputs": [{"internalType": "uint256[]", "name": "_tokenIds", "type": "uint256[]"}], "name": "batchOwnerOf",
         "outputs": [{"internalType": "address[]", "name": "owners_", "type": "address[]"}], "stateMutability": "view",
         "type": "function"},
        {"inputs": [{"internalType": "uint256", "name": "_tokenId", "type": "uint256"}], "name": "getAavegotchi",
         "outputs": [{"components": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"},
                                     {"internalType": "string", "name": "name", "type": "string"},
                                     {"internalType": "address", "name": "owner", "type": "address"},
                                     {"internalType": "uint256", "name": "randomNumber", "type": "uint256"},
                                     {"internalType": "uint256", "name": "status", "type": "uint256"},
                                     {"internalType": "int16[6]", "name": "numericTraits", "type": "int16[6]"},
                                     {"internalType": "int16[6]", "name": "modifiedNumericTraits", "type": "int16[6]"},
                                     {"internalType": "uint16[16]", "name": "equippedWearables", "type": "uint16[16]"},
                                     {"internalType": "address", "name": "collateral", "type": "address"},
                                     {"internalType": "address", "name": "escrow", "type": "address"},
                                     {"internalType": "uint256", "name": "stakedAmount", "type": "uint256"},
                                     {"internalType": "uint256", "name": "minimumStake", "type": "uint256"},
                                     {"internalType": "uint256", "name": "kinship", "type": "uint256"},
                                     {"internalType": "uint256", "name": "lastInteracted", "type": "uint256"},
                                     {"internalType": "uint256", "name": "experience", "type": "uint256"},
                                     {"internalType": "uint256", "name": "toNextLevel", "type": "uint256"},
                                     {"internalType": "uint256", "name": "usedSkillPoints", "type": "uint256"},
                                     {"internalType": "uint256", "name": "level", "type": "uint256"},
                                     {"internalType": "uint256", "name": "hauntId", "type": "uint256"},
                                     {"internalType": "uint256", "name": "baseRarityScore", "type": "uint256"},
                                     {"internalType": "uint256", "name": "modifiedRarityScore", "type": "uint256"},
                                     {"internalType": "bool", "name": "locked", "type": "bool"}, {"components": [
                 {"internalType": "uint256", "name": "balance", "type": "uint256"},
                 {"internalType": "uint256", "name": "itemId", "type": "uint256"}, {
                     "components": [{"internalType": "string", "name": "name", "type": "string"},
                                    {"internalType": "string", "name": "description", "type": "string"},
                                    {"internalType": "string", "name": "author", "type": "string"},
                                    {"internalType": "int8[6]", "name": "traitModifiers", "type": "int8[6]"},
                                    {"internalType": "bool[16]", "name": "slotPositions", "type": "bool[16]"},
                                    {"internalType": "uint8[]", "name": "allowedCollaterals", "type": "uint8[]"}, {
                                        "components": [{"internalType": "uint8", "name": "x", "type": "uint8"},
                                                       {"internalType": "uint8", "name": "y", "type": "uint8"},
                                                       {"internalType": "uint8", "name": "width", "type": "uint8"},
                                                       {"internalType": "uint8", "name": "height", "type": "uint8"}],
                                        "internalType": "struct Dimensions", "name": "dimensions", "type": "tuple"},
                                    {"internalType": "uint256", "name": "ghstPrice", "type": "uint256"},
                                    {"internalType": "uint256", "name": "maxQuantity", "type": "uint256"},
                                    {"internalType": "uint256", "name": "totalQuantity", "type": "uint256"},
                                    {"internalType": "uint32", "name": "svgId", "type": "uint32"},
                                    {"internalType": "uint8", "name": "rarityScoreModifier", "type": "uint8"},
                                    {"internalType": "bool", "name": "canPurchaseWithGhst", "type": "bool"},
                                    {"internalType": "uint16", "name": "minLevel", "type": "uint16"},
                                    {"internalType": "bool", "name": "canBeTransferred", "type": "bool"},
                                    {"internalType": "uint8", "name": "category", "type": "uint8"},
                                    {"internalType": "int16", "name": "kinshipBonus", "type": "int16"},
                                    {"internalType": "uint32", "name": "experienceBonus", "type": "uint32"}],
                     "internalType": "struct ItemType", "name": "itemType", "type": "tuple"}],
                                                                                                  "internalType": "struct ItemTypeIO[]",
                                                                                                  "name": "items",
                                                                                                  "type": "tuple[]"}],
                      "internalType": "struct AavegotchiInfo", "name": "aavegotchiInfo_", "type": "tuple"}],
         "stateMutability": "view", "type": "function"},
        {"inputs": [{"internalType": "uint256", "name": "_tokenId", "type": "uint256"}], "name": "getApproved",
         "outputs": [{"internalType": "address", "name": "approved_", "type": "address"}], "stateMutability": "view",
         "type": "function"}, {"inputs": [{"internalType": "address", "name": "_owner", "type": "address"},
                                          {"internalType": "address", "name": "_operator", "type": "address"}],
                               "name": "isApprovedForAll",
                               "outputs": [{"internalType": "bool", "name": "approved_", "type": "bool"}],
                               "stateMutability": "view", "type": "function"}, {
            "inputs": [{"internalType": "address", "name": "_owner", "type": "address"},
                       {"internalType": "address", "name": "_operator", "type": "address"}],
            "name": "isPetOperatorForAll", "outputs": [{"internalType": "bool", "name": "approved_", "type": "bool"}],
            "stateMutability": "view", "type": "function"},
        {"inputs": [], "name": "name", "outputs": [{"internalType": "string", "name": "", "type": "string"}],
         "stateMutability": "view", "type": "function"},
        {"inputs": [{"internalType": "uint256", "name": "_tokenId", "type": "uint256"}], "name": "ownerOf",
         "outputs": [{"internalType": "address", "name": "owner_", "type": "address"}], "stateMutability": "view",
         "type": "function"}, {"inputs": [{"internalType": "address", "name": "_from", "type": "address"},
                                          {"internalType": "address", "name": "_to", "type": "address"},
                                          {"internalType": "uint256[]", "name": "_tokenIds", "type": "uint256[]"},
                                          {"internalType": "bytes", "name": "_data", "type": "bytes"}],
                               "name": "safeBatchTransferFrom", "outputs": [], "stateMutability": "nonpayable",
                               "type": "function"}, {
            "inputs": [{"internalType": "address", "name": "_from", "type": "address"},
                       {"internalType": "address", "name": "_to", "type": "address"},
                       {"internalType": "uint256", "name": "_tokenId", "type": "uint256"}], "name": "safeTransferFrom",
            "outputs": [], "stateMutability": "nonpayable", "type": "function"}, {
            "inputs": [{"internalType": "address", "name": "_from", "type": "address"},
                       {"internalType": "address", "name": "_to", "type": "address"},
                       {"internalType": "uint256", "name": "_tokenId", "type": "uint256"},
                       {"internalType": "bytes", "name": "_data", "type": "bytes"}], "name": "safeTransferFrom",
            "outputs": [], "stateMutability": "nonpayable", "type": "function"}, {
            "inputs": [{"internalType": "address", "name": "_operator", "type": "address"},
                       {"internalType": "bool", "name": "_approved", "type": "bool"}], "name": "setApprovalForAll",
            "outputs": [], "stateMutability": "nonpayable", "type": "function"}, {
            "inputs": [{"internalType": "address", "name": "_operator", "type": "address"},
                       {"internalType": "bool", "name": "_approved", "type": "bool"}], "name": "setPetOperatorForAll",
            "outputs": [], "stateMutability": "nonpayable", "type": "function"},
        {"inputs": [], "name": "symbol", "outputs": [{"internalType": "string", "name": "", "type": "string"}],
         "stateMutability": "view", "type": "function"},
        {"inputs": [{"internalType": "uint256", "name": "_index", "type": "uint256"}], "name": "tokenByIndex",
         "outputs": [{"internalType": "uint256", "name": "tokenId_", "type": "uint256"}], "stateMutability": "view",
         "type": "function"},
        {"inputs": [{"internalType": "address", "name": "_owner", "type": "address"}], "name": "tokenIdsOfOwner",
         "outputs": [{"internalType": "uint32[]", "name": "tokenIds_", "type": "uint32[]"}], "stateMutability": "view",
         "type": "function"}, {"inputs": [{"internalType": "address", "name": "_owner", "type": "address"},
                                          {"internalType": "uint256", "name": "_index", "type": "uint256"}],
                               "name": "tokenOfOwnerByIndex",
                               "outputs": [{"internalType": "uint256", "name": "tokenId_", "type": "uint256"}],
                               "stateMutability": "view", "type": "function"},
        {"inputs": [{"internalType": "uint256", "name": "_tokenId", "type": "uint256"}], "name": "tokenURI",
         "outputs": [{"internalType": "string", "name": "", "type": "string"}], "stateMutability": "pure",
         "type": "function"}, {"inputs": [], "name": "totalSupply",
                               "outputs": [{"internalType": "uint256", "name": "totalSupply_", "type": "uint256"}],
                               "stateMutability": "view", "type": "function"}, {
            "inputs": [{"internalType": "address", "name": "_from", "type": "address"},
                       {"internalType": "address", "name": "_to", "type": "address"},
                       {"internalType": "uint256", "name": "_tokenId", "type": "uint256"}], "name": "transferFrom",
            "outputs": [], "stateMutability": "nonpayable", "type": "function"}]
abi2 = [{"anonymous": False,
         "inputs": [{"indexed": True, "internalType": "uint256", "name": "_tokenId", "type": "uint256"}],
         "name": "ClaimAavegotchi", "type": "event"}, {"anonymous": False, "inputs": [
    {"indexed": True, "internalType": "uint256", "name": "_tokenId", "type": "uint256"},
    {"indexed": False, "internalType": "uint256", "name": "_time", "type": "uint256"}], "name": "LockAavegotchi",
                                                       "type": "event"}, {"anonymous": False, "inputs": [
    {"indexed": True, "internalType": "uint256", "name": "_tokenId", "type": "uint256"},
    {"indexed": False, "internalType": "string", "name": "_oldName", "type": "string"},
    {"indexed": False, "internalType": "string", "name": "_newName", "type": "string"}], "name": "SetAavegotchiName",
                                                                          "type": "event"}, {"anonymous": False,
                                                                                             "inputs": [
                                                                                                 {"indexed": True,
                                                                                                  "internalType": "uint256",
                                                                                                  "name": "_batchId",
                                                                                                  "type": "uint256"},
                                                                                                 {"indexed": False,
                                                                                                  "internalType": "uint256[]",
                                                                                                  "name": "tokenIds",
                                                                                                  "type": "uint256[]"}],
                                                                                             "name": "SetBatchId",
                                                                                             "type": "event"},
        {"anonymous": False,
         "inputs": [{"indexed": True, "internalType": "uint256", "name": "_tokenId", "type": "uint256"},
                    {"indexed": False, "internalType": "int16[4]", "name": "_values", "type": "int16[4]"}],
         "name": "SpendSkillpoints", "type": "event"}, {"anonymous": False, "inputs": [
        {"indexed": True, "internalType": "uint256", "name": "_tokenId", "type": "uint256"},
        {"indexed": False, "internalType": "uint256", "name": "_time", "type": "uint256"}], "name": "UnLockAavegotchi",
                                                        "type": "event"},
        {"inputs": [{"internalType": "uint256", "name": "_experience", "type": "uint256"}], "name": "aavegotchiLevel",
         "outputs": [{"internalType": "uint256", "name": "level_", "type": "uint256"}], "stateMutability": "pure",
         "type": "function"},
        {"inputs": [{"internalType": "string", "name": "_name", "type": "string"}], "name": "aavegotchiNameAvailable",
         "outputs": [{"internalType": "bool", "name": "available_", "type": "bool"}], "stateMutability": "view",
         "type": "function"},
        {"inputs": [{"internalType": "uint256", "name": "_tokenId", "type": "uint256"}], "name": "availableSkillPoints",
         "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "stateMutability": "view",
         "type": "function"}, {"inputs": [{"internalType": "int16[6]", "name": "_numericTraits", "type": "int16[6]"}],
                               "name": "baseRarityScore",
                               "outputs": [{"internalType": "uint256", "name": "rarityScore_", "type": "uint256"}],
                               "stateMutability": "pure", "type": "function"}, {
            "inputs": [{"internalType": "uint256", "name": "_tokenId", "type": "uint256"},
                       {"internalType": "uint256", "name": "_option", "type": "uint256"},
                       {"internalType": "uint256", "name": "_stakeAmount", "type": "uint256"}],
            "name": "claimAavegotchi", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
        {"inputs": [], "name": "currentHaunt",
         "outputs": [{"internalType": "uint256", "name": "hauntId_", "type": "uint256"}, {
             "components": [{"internalType": "uint256", "name": "hauntMaxSize", "type": "uint256"},
                            {"internalType": "uint256", "name": "portalPrice", "type": "uint256"},
                            {"internalType": "bytes3", "name": "bodyColor", "type": "bytes3"},
                            {"internalType": "uint24", "name": "totalCount", "type": "uint24"}],
             "internalType": "struct Haunt", "name": "haunt_", "type": "tuple"}], "stateMutability": "view",
         "type": "function"},
        {"inputs": [{"internalType": "uint256", "name": "_tokenId", "type": "uint256"}], "name": "getNumericTraits",
         "outputs": [{"internalType": "int16[6]", "name": "numericTraits_", "type": "int16[6]"}],
         "stateMutability": "view", "type": "function"}, {"inputs": [], "name": "ghstAddress", "outputs": [
        {"internalType": "address", "name": "contract_", "type": "address"}], "stateMutability": "view",
                                                          "type": "function"},
        {"inputs": [{"internalType": "uint256[]", "name": "_tokenIds", "type": "uint256[]"}], "name": "interact",
         "outputs": [], "stateMutability": "nonpayable", "type": "function"},
        {"inputs": [{"internalType": "uint256", "name": "_tokenId", "type": "uint256"}], "name": "kinship",
         "outputs": [{"internalType": "uint256", "name": "score_", "type": "uint256"}], "stateMutability": "view",
         "type": "function"}, {"inputs": [{"internalType": "uint256", "name": "_tokenId", "type": "uint256"}],
                               "name": "modifiedTraitsAndRarityScore",
                               "outputs": [{"internalType": "int16[6]", "name": "numericTraits_", "type": "int16[6]"},
                                           {"internalType": "uint256", "name": "rarityScore_", "type": "uint256"}],
                               "stateMutability": "view", "type": "function"},
        {"inputs": [{"internalType": "uint256", "name": "_tokenId", "type": "uint256"}],
         "name": "portalAavegotchiTraits", "outputs": [{"components": [
            {"internalType": "uint256", "name": "randomNumber", "type": "uint256"},
            {"internalType": "int16[6]", "name": "numericTraits", "type": "int16[6]"},
            {"internalType": "address", "name": "collateralType", "type": "address"},
            {"internalType": "uint256", "name": "minimumStake", "type": "uint256"}],
            "internalType": "struct PortalAavegotchiTraitsIO[10]",
            "name": "portalAavegotchiTraits_", "type": "tuple[10]"}],
         "stateMutability": "view", "type": "function"},
        {"inputs": [{"internalType": "int16[6]", "name": "_numericTraits", "type": "int16[6]"}],
         "name": "rarityMultiplier", "outputs": [{"internalType": "uint256", "name": "multiplier_", "type": "uint256"}],
         "stateMutability": "pure", "type": "function"},
        {"inputs": [{"internalType": "uint256", "name": "_tokenId", "type": "uint256"}], "name": "realmInteract",
         "outputs": [], "stateMutability": "nonpayable", "type": "function"}, {"inputs": [], "name": "revenueShares",
                                                                               "outputs": [{"components": [
                                                                                   {"internalType": "address",
                                                                                    "name": "burnAddress",
                                                                                    "type": "address"},
                                                                                   {"internalType": "address",
                                                                                    "name": "daoAddress",
                                                                                    "type": "address"},
                                                                                   {"internalType": "address",
                                                                                    "name": "rarityFarming",
                                                                                    "type": "address"},
                                                                                   {"internalType": "address",
                                                                                    "name": "pixelCraft",
                                                                                    "type": "address"}],
                                                                                   "internalType": "struct AavegotchiGameFacet.RevenueSharesIO",
                                                                                   "name": "",
                                                                                   "type": "tuple"}],
                                                                               "stateMutability": "view",
                                                                               "type": "function"}, {
            "inputs": [{"internalType": "uint256", "name": "_tokenId", "type": "uint256"},
                       {"internalType": "string", "name": "_name", "type": "string"}], "name": "setAavegotchiName",
            "outputs": [], "stateMutability": "nonpayable", "type": "function"},
        {"inputs": [{"internalType": "address", "name": "_realm", "type": "address"}], "name": "setRealmAddress",
         "outputs": [], "stateMutability": "nonpayable", "type": "function"}, {
            "inputs": [{"internalType": "uint256", "name": "_tokenId", "type": "uint256"},
                       {"internalType": "int16[4]", "name": "_values", "type": "int16[4]"}], "name": "spendSkillPoints",
            "outputs": [], "stateMutability": "nonpayable", "type": "function"}, {
            "inputs": [{"internalType": "address", "name": "_owner", "type": "address"},
                       {"internalType": "uint256", "name": "_count", "type": "uint256"},
                       {"internalType": "uint256", "name": "_skip", "type": "uint256"},
                       {"internalType": "bool", "name": "all", "type": "bool"}], "name": "tokenIdsWithKinship",
            "outputs": [{"components": [{"internalType": "uint256", "name": "tokenId", "type": "uint256"},
                                        {"internalType": "uint256", "name": "kinship", "type": "uint256"},
                                        {"internalType": "uint256", "name": "lastInteracted", "type": "uint256"}],
                         "internalType": "struct AavegotchiGameFacet.TokenIdsWithKinship[]",
                         "name": "tokenIdsWithKinship_", "type": "tuple[]"}], "stateMutability": "view",
            "type": "function"},
        {"inputs": [{"internalType": "uint256", "name": "_experience", "type": "uint256"}], "name": "xpUntilNextLevel",
         "outputs": [{"internalType": "uint256", "name": "requiredXp_", "type": "uint256"}], "stateMutability": "pure",
         "type": "function"}]

abi = [{"inputs": [{"internalType": "bytes32", "name": "_svgType", "type": "bytes32"},
                   {"internalType": "uint256", "name": "_numLayers", "type": "uint256"}], "name": "deleteLastSvgLayers",
        "outputs": [], "stateMutability": "nonpayable", "type": "function"},
       {"inputs": [{"internalType": "uint256", "name": "_tokenId", "type": "uint256"}], "name": "getAavegotchiSvg",
        "outputs": [{"internalType": "string", "name": "ag_", "type": "string"}], "stateMutability": "view",
        "type": "function"},
       {"inputs": [{"internalType": "uint256", "name": "_itemId", "type": "uint256"}], "name": "getItemSvg",
        "outputs": [{"internalType": "string", "name": "ag_", "type": "string"}], "stateMutability": "view",
        "type": "function"}, {"inputs": [], "name": "getNextSleeveId",
                              "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
                              "stateMutability": "view", "type": "function"}, {
           "inputs": [{"internalType": "bytes32", "name": "_svgType", "type": "bytes32"},
                      {"internalType": "uint256", "name": "_itemId", "type": "uint256"}], "name": "getSvg",
           "outputs": [{"internalType": "string", "name": "svg_", "type": "string"}], "stateMutability": "view",
           "type": "function"}, {"inputs": [{"internalType": "bytes32", "name": "_svgType", "type": "bytes32"},
                                            {"internalType": "uint256[]", "name": "_itemIds", "type": "uint256[]"}],
                                 "name": "getSvgs",
                                 "outputs": [{"internalType": "string[]", "name": "svgs_", "type": "string[]"}],
                                 "stateMutability": "view", "type": "function"},
       {"inputs": [{"internalType": "uint256", "name": "_tokenId", "type": "uint256"}], "name": "portalAavegotchisSvg",
        "outputs": [{"internalType": "string[10]", "name": "svg_", "type": "string[10]"}], "stateMutability": "view",
        "type": "function"}, {"inputs": [{"internalType": "uint256", "name": "_hauntId", "type": "uint256"},
                                         {"internalType": "address", "name": "_collateralType", "type": "address"},
                                         {"internalType": "int16[6]", "name": "_numericTraits", "type": "int16[6]"},
                                         {"internalType": "uint16[16]", "name": "equippedWearables",
                                          "type": "uint16[16]"}], "name": "previewAavegotchi",
                              "outputs": [{"internalType": "string", "name": "ag_", "type": "string"}],
                              "stateMutability": "view", "type": "function"}, {
           "inputs": [{"internalType": "uint256[]", "name": "_itemIds", "type": "uint256[]"}, {
               "components": [{"internalType": "uint8", "name": "x", "type": "uint8"},
                              {"internalType": "uint8", "name": "y", "type": "uint8"},
                              {"internalType": "uint8", "name": "width", "type": "uint8"},
                              {"internalType": "uint8", "name": "height", "type": "uint8"}],
               "internalType": "struct Dimensions[]", "name": "_dimensions", "type": "tuple[]"}],
           "name": "setItemsDimensions", "outputs": [], "stateMutability": "nonpayable", "type": "function"}, {
           "inputs": [{"components": [{"internalType": "uint256", "name": "sleeveId", "type": "uint256"},
                                      {"internalType": "uint256", "name": "wearableId", "type": "uint256"}],
                       "internalType": "struct SvgFacet.Sleeve[]", "name": "_sleeves", "type": "tuple[]"}],
           "name": "setSleeves", "outputs": [], "stateMutability": "nonpayable", "type": "function"}, {
           "inputs": [{"internalType": "string", "name": "_svg", "type": "string"}, {
               "components": [{"internalType": "bytes32", "name": "svgType", "type": "bytes32"},
                              {"internalType": "uint256[]", "name": "sizes", "type": "uint256[]"}],
               "internalType": "struct LibSvg.SvgTypeAndSizes[]", "name": "_typesAndSizes", "type": "tuple[]"}],
           "name": "storeSvg", "outputs": [], "stateMutability": "nonpayable", "type": "function"}, {
           "inputs": [{"internalType": "string", "name": "_svg", "type": "string"}, {
               "components": [{"internalType": "bytes32", "name": "svgType", "type": "bytes32"},
                              {"internalType": "uint256[]", "name": "ids", "type": "uint256[]"},
                              {"internalType": "uint256[]", "name": "sizes", "type": "uint256[]"}],
               "internalType": "struct LibSvg.SvgTypeAndIdsAndSizes[]", "name": "_typesAndIdsAndSizes",
               "type": "tuple[]"}], "name": "updateSvg", "outputs": [], "stateMutability": "nonpayable",
           "type": "function"}]